### PR TITLE
fix templates && translations

### PR DESCRIPTION
**Pull request by 221V**
few little fixes

### CODE REVIEW

**Comment by 221V** [comment]
also question -
@Shadowss what do you think about idea to rewrite server installer in compiled language like C or D (dlang) ?

cause php sucks when needs to generate big map ((

**Comment by Shadowss** [comment]
Sounds good. I can give you acces to merge directly

**Comment by andreapavoni** [comment]
> also question - @Shadowss what do you think about idea to rewrite server installer in compiled language like C or D (dlang) ?
> 
> cause php sucks when needs to generate big map ((

I’d suggest Go or Rust for this task, they’re easier to pack an helper binary.

on a side note, I already have some code in Rust to achieve this and other Travian-related stuff.

**Comment by Shadowss** [comment]
> > also question - @Shadowss what do you think about idea to rewrite server installer in compiled language like C or D (dlang) ?
> 
> > 
> 
> > cause php sucks when needs to generate big map ((
> 
> 
> 
> I’d suggest Go or Rust for this task, they’re easier to pack an helper binary.
> 
> 
> 
> on a side note, I already have some code in Rust to achieve this and other Travian-related stuff.

Send us the code to review

**Pull request merged**
